# Generated by Django 3.1.7 on 2022-03-14 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('join', models.DateField(default=datetime.datetime.now)),
                ('phone', models.IntegerField()),
                ('dni', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
